# Run configuration
Run_Name : "test"
Sample_Info : "sampleInfo/test.sampleInfo.csv"
Supplemental_Info : "sampleInfo/test.supp.csv"
Panel : "panel.test"
Panel_Path : "panels/panel.test.csv"
RefGenome : "hg38"
Platform : "illumina"

# Sequence files
Seq_Path: "analysis/test/input_data/"
R1: "test.R1.fastq.gz"
R2: "test.R2.fastq.gz"
I1: "test.I1.fastq.gz"
I2: "test.I2.fastq.gz"

# SampleInfo formating
Sample_Name_Column : "sampleName"
BC5p : "sampleInfo:barcode1"
BC3p : "sampleInfo:barcode2"

# Sequence information, leave empty "" if using different platform 
## Illumina Platform
R1_Leading_Trim : "."
R1_Overreading_Trim : "AGATCGGAAGAGCACACGTC"
R2_Leading_Trim : "."
R2_Overreading_Trim : "AGATCGGAAGAGCGTCGTGT"
## Nanopore
Init_Sense : "AATGATACGGCGACCACCGAGATCTACAC"
Init_Antisense : "CAAGCAGAAGACGGCATACGAGAT"
TAG_5p_Seq : "ACACTCTTTCCCTACACGACGCTCTTCCGATCT"
TAG_3p_Seq : "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"


# ------------------------------------------------------------------------------
# TsAP configuration
Read_Types : ["R1", "R2", "I1", "I2"]
Genomic_Reads : ["R1", "R2"]

# Demultiplexing parameters
barcode1Length : 12
barcode2Length : 12
barcode1 : "I1"
barcode2 : "I2"
bc1Mismatch : 1
bc2Mismatch : 1
demultiCores : 4

# Sequence trimming
## R1 sequence
R1leadMismatch : 0
R1overMismatch : 1
R1overMaxLength : 20
## R2 sequence
R2leadMismatch : 0
R2overMismatch : 1
R2overMaxLength : 20

# Nanopore Trimming Params
Init_Error : 0.2
Min_Size : 500
Tag_Error : 0.2

# Uniting paired-end Reads
pearParams : "-p 1.0 -n 30"

# Reference Alignment
# Panel param
Max_Length : 400
## Illumina BWA params
BWAparams : "-k 30 -w 150"
## Nanopore BWA params
npBWAparams : "-x ont2d"

# Post-Alignment Processing
maxDistFromEdit : 20

# Summary Report Options
format : "pdf"
figures : FALSE
reportData : FALSE
suppFile : FALSE
discussion :
    include : FALSE
    path : "."
methods : FALSE
signature : 
    include : FALSE
    positions :
        analyst : ["Bioinformatic Analyst", "Christopher Nobles, Ph.D."]